### ISSUE TITLE
fehler in make

### ISSUE THREAD

**Issue by a-wendler** [deutsche-nationalbibliothek/gnd-dashboard#18]
Kann es sein, dass es einen Fehler im makefile gibt?

Dort werden ja die ganze .9-Felder einzeln ausgelesen.

In den TITLE_LINK_OBJS sind das 27 Felder, weiter unten beim Erzeugen der CSVs werden aber 29 Dateien erzeugt (+044H,044K)

Wenn ich den Code richtig verstehe, werden die doch nicht mit in 0XXX_9.csv konkatiniert.

Entweder diese Felder werde nicht benötigt, dann müssen Zeilen 98 und 99 weg oder sie müssen oben mit in die TITLE_LINK_OBJS

PS. Bin darauf gekommen, weil ich gerade mal versuchen wollte #7 umzusetzen.

**Comment by a-wendler** [comment]
erledigt. das sind die maschinellen verknüpfungen, die extra behandelt werden. sorry.

**Comment by niko2342** [comment]
Ich werde das Makefile demnächst überarbeiten und vereinfachen. Dabei werde ich auch gleich ein paar Kommentare hinzufügen.
