### ISSUE TITLE
Auswertungsfehler

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/gnd-dashboard#3]
> es kommt mir etwas seltsam vor, dass bei den Tf-Sätzen 00754023x die Top10 mit angeblich über 4000 Verwendungen anführen soll. wenn ich die idn im katalog suche, kriege ich nur 20 ergebnisse. gibt es dafür eine erklärung?

siehe https://github.com/buchmuseum/GND_Dashboard/issues/4

**Comment by a-wendler** [comment]
Erledigt. Es stimmt doch. Ich habe es nachrecherchiert. Das Buchmuseum hat damals offenbar etliche tausend Objekte von dieser Buchkunstausstellung in den Bestand übernommen und bei allen Exemplaren wurde diese Verknüpfung eingefügt.
