### ISSUE TITLE
Neues Datenverzeichnis

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/gnd-dashboard#9]
CSV-Dateien aus  `stats/` und `dashboard/`  nach `data/` verschieben.

**Comment by a-wendler** [comment]
kümmerst du, lieber @niko2342 , dich um deine Scripte und um makefile? Dann passe ich das dashboard-Skript an und verschiebe die entsprechenden dateien.

ich hatte beim aktualisieren des dashboards im juni probleme mit den pfaden in deinen Skript-Dateien, weil auf meinem unix die pfade offenbar relativ zu den skript-dateien gelesen wurden und nicht relativ zum makefile.

**Comment by ramonvoges** [comment]
Lieber André,

während Deines Urlaubs haben Nico und ich bereits einige Issues erstellt und tlw. auch schon zugeordnet. Vielleicht beantwortet das schon die eine oder andere Deiner Fragen. 

Herzlich
Ramon
